version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/var/www/html
    depends_on:
      - database
  web:
    build:
      context: ./web
    ports:
      - 4200:4200
    environment:
      NODE_ENV: development
    volumes:
      - ./web:/app
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pokedex
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
